### PR TITLE
switch to python 3

### PR DESCRIPTION
**Pull request by scoutsaachi**
Switch TICC solver to python 3

The mammoth changes in TICC_helper are just converting all the indentation to spaces instead of a mix of tabs and spaces (which python 3 will break on)

For some reason this change breaks unit tests, but only slightly? The assignments stay the same, but the cluster MRFs are ever so slightly different: 5.9496 vs 5.9497 on the second diagonal entry (which shouldn't matter anyway?).

### CODE REVIEW

**Comment by RasmusFonseca** [comment]
Does this break py27 compatibility? I think I kept 
```python
try:
  import builtins as bt
except ImportError:
  import __builtin__ as bt
```
and then it still worked in 2.7

**Comment by RasmusFonseca** [comment]
That's all assuming theres a good reason to not just change `bt.len` to `len` which is the only use for the `builtins` import I think.

**Comment by scoutsaachi** [comment]
@davidhallac Unless you overrode bt.len somewhere and I didn't catch it, I don't think we need the builtins import

**Comment by davidhallac** [comment]
@scoutsaachi Nope, I didn't override bt.len. I think we should be able to use the default one and remove builtin from the distribution

**Pull request merged**
